{
	"version": 1517493627,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/sangrepiso-sheet0.png",
		"images/sangrepiso-sheet1.png",
		"images/sangresalpicada.png",
		"images/sp_camera-sheet0.png",
		"images/sp_floor-sheet0.png",
		"images/sp_stairs-sheet0.png",
		"images/sp_solid-sheet0.png",
		"images/sp_player-sheet0.png",
		"images/sp_weapons-sheet0.png",
		"images/sp_door_blocked-sheet0.png",
		"images/sp_door-sheet0.png",
		"images/sp_bullet-sheet0.png",
		"media/disparo escopeta.ogg",
		"media/disparo pistola.ogg",
		"media/escalera un paso.ogg",
		"media/mapa limpiado.ogg",
		"media/sangre.ogg",
		"media/caminar.ogg",
		"media/masacre - 27-01-18 19.41.m4a",
		"media/masacre - 27-01-18 19.41.ogg",
		"media/creditos.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}