{
	"version": 1517160696,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/solido-sheet0.png",
		"images/puerta-sheet0.png",
		"images/bala-sheet0.png",
		"images/armaplayer-sheet0.png",
		"images/mafioso_pistola-sheet0.png",
		"images/camara-sheet0.png",
		"images/sangresalpicada.png",
		"images/sangrepiso-sheet0.png",
		"images/sangrepiso-sheet1.png",
		"images/armageneral-sheet0.png",
		"images/fondo0.png",
		"images/objeto-sheet0.png",
		"images/sprite-sheet0.png",
		"media/disparo escopeta.ogg",
		"media/disparo pistola.ogg",
		"media/escalera un paso.ogg",
		"media/mapa limpiado.ogg",
		"media/sangre.ogg",
		"media/caminar.ogg",
		"media/masacre - 27-01-18 19.41.m4a",
		"media/masacre - 27-01-18 19.41.ogg",
		"media/creditos.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"pathfind.js"
	]
}